### ISSUE TITLE
"Remove all envelopes for selected tracks" does not remove send volume

### ISSUE THREAD

**Issue by bFooz** [reaper-oss/sws#918] opened 2017-10-30 14:02 UTC

**Comment by nofishonfriday** [comment] 2017-11-01 12:08
Confirmed.
And, what also shouldn't hapen, when running this action and having a track selected that has receives it deletes the send envelopes on the sending track.

Probably because send envelopes are stored on the receiving track's chunk and [RemoveEnvelopes](https://github.com/reaper-oss/sws/blob/a0660cc0dd49a392e3a4c64962c25580048d0986/SnM/SnM_Chunk.cpp#L767) called in [RemoveAllEnvSelTracks](https://github.com/reaper-oss/sws/blob/1104dcdbe7ac7d5b4600e96814237fd549a5a356/SnM/SnM_Track.cpp#L581) doesn't account for this.

I've been looking into this but I don't understand the ParserPatcher good enough currently to fix.

**Comment by nofishonfriday** [comment] 2017-11-06 16:38
I'm not really happy with the thought that this action can potentially create havoc (unintentionally deleting send envelopes).

So, I'm wondering is anyone able and plan to fix ?
Otherwise I think it should rather be disabled / hidden.
Thoughts ?

**Comment by veto-gh** [comment] 2017-11-09 22:34
Would like to have a deeper look at the chunk parser class some day.

> And, what also shouldn't hapen, when running this action and having a track selected that has receives it deletes the send envelopes on the sending track(s).

In think this would not even be the hardest part, but to prevent the behaviour bFooz is describing we would need to parse all tracks and look for receives of selected tracks.

Other than that there is this (but maybe even an uglier hack):
(EEL-script:)
```
Undo_BeginBlock();
PreventUIRefresh(1);
  
i=0;
loop(CountSelectedTracks(0),
  curTrk=GetSelectedTrack(0,i);
  j=0;
  while(CountTrackEnvelopes(curTrk)>0 && j<10000) (    // j<10000 just for safety reasons
    Main_OnCommand(41864,0);   // Track: Select next envelope
    DeleteEnvelopePointRange(GetSelectedEnvelope(0),-1000000000,1000000000);
    Main_OnCommand(40065,0);   // Envelope: Clear envelope
    j+=1;
  );
  i+=1;
);


Undo_EndBlock(UndoDescription,-1);
PreventUIRefresh(-1);
```


We need to remove all envelope points first to make Reaper not spawn a dialog on running action 40065.

**Comment by veto-gh** [comment] 2017-11-10 00:13
I would love to have a deeper look at the chunk parser class some day.

> And, what also shouldn't hapen, when running this action and having a track selected that has receives it deletes the send envelopes on the sending track(s).

In think this would not even be the hardest part. But to prevent the behaviour bFooz is describing we would need to parse all tracks in the project and look for receives of selected tracks.

Other than that there is this:
(EEL-script:)
```
function eelBegin(UndoYesNo , PrevYesNo) (
	UndoYesNo ? (Undo_BeginBlock(););
	PrevYesNo ? (PreventUIRefresh(1););
);
function eelEnd(UndoYesNo , PrevYesNo , UndoDescription) (
	UndoYesNo ? (Undo_EndBlock(UndoDescription,-1););
	PrevYesNo ? (PreventUIRefresh(-1););
);
function cmd(cmd) (
	match("%s",cmd) ? Main_OnCommand(NamedCommandLookup(cmd),0) : Main_OnCommand(cmd,0);
);


eelBegin(1,1);
cmd(41148);  // Envelope: Show all envelopes for (selected) tracks
i=0;
loop(CountSelectedTracks(0),
	tr=GetSelectedTrack(0,i);
	j=0;
	loop(CountTrackEnvelopes(tr),
		e=GetTrackEnvelope(tr,0);
		SetCursorContext(2,e);   // select envelope
		DeleteEnvelopePointRange(GetSelectedEnvelope(0),-1000000000,1000000000);
		cmd(40065);   // Envelope: Clear (selected) envelope
		j+=1;
	);
	i+=1;
);
eelEnd(1,1,"Remove all envelopes for selected tracks");
```

But I consider that a hack because of 2 reasons. Firstly we need to remove all envelope points to make Reaper not spawn a dialog on running action 40065 (Envelope: Clear (selected) envelope) and secondly to run that action we need to select an envelope first. And to select an envelope it must be made visible.

Anyway it works and it may still be a better approach than to loop through chunks of all tracks.

If anybody of the team wants to see it in the extension just drop a short line and I add it.

**Comment by nofishonfriday** [comment] 2017-11-10 01:13
Thanks for chiming in Veto.

Just as a note:
> But to prevent the behaviour bFooz is describing we would need to parse all tracks in the project and look for receives of selected tracks.

Actually to get the receiving  tracks of a track we wouldn't need to do chunk parsing, this can be done with the API.
Something like this:

```
int trackNumSends = GetTrackNumSends(selTrack, 0);
for (int i = 0; i < trackNumSends; i++) { 
 // iterate through destination tracks
   MediaTrack* destTrack = (MediaTrack*)GetSetTrackSendInfo(selTrack, 0, i, "P_DESTTRACK", NULL);
   SetTrackSelected(destTrack, true); // for testing
}

```

**Comment by veto-gh** [comment] 2017-11-10 17:09
I missed that. Thank you Nofish, that's a huge help!

**Comment by nofishonfriday** [comment] 2017-11-10 21:27
You're welcome.
As for integrating your script in SWS, personally I'm happy with any alternative that doesn't have the 'side effects' this action has.
Iow, I'd say go for it. :)

**Comment by veto-gh** [comment] 2017-11-12 18:37
I went the short road, need to comprehend the ParserPatcher class a bit more first to do anything serious (I would also have needed to look for automation items of every removed envelope of every selected track, which are stored on level 1 of the track chunk. Otherwise they remain orphaned in the project)

**Comment by nofishonfriday** [comment] 2019-11-10 18:09
fixed/merged.

**Closed by nofishonfriday** 2019-11-10 18:09 UTC
