### ISSUE TITLE
"Reposition selected items..." on Mac not working for "item start"

### ISSUE THREAD

**Issue by leonardobarragan** [reaper-oss/sws#819] opened 2016-07-19 00:58 UTC
OS X 10.11.5
sws-v2.8.3.0
Reaper v5.20/64

"Reposition selected items..."  When selecting "item start", "item end" remains selected and the action will only work as "item end"

**Comment by X-Raym** [comment] 2016-11-03 23:34
Confirmed.

Meanwhile, you can envisage use these [scripts](https://www.extremraym.com/en/downloads/reascripts-space-items-pack/).

related issue: https://github.com/reaper-oss/sws/issues/811

**Comment by X-Raym** [comment] 2016-11-09 23:10
**@leonardobarragan** 
I created alternatives scripts for the item start option. Check the link put in my previous post. Maybe it can help you.

**Comment by swstim** [comment] 2017-03-26 02:59
Closed as duplicate of #811

**Closed by swstim** 2017-03-26 02:59 UTC
