### ISSUE TITLE
(MAIN) SWS/FNG: Transpose selected MIDI items - all variations only work on the first selected item

### ISSUE THREAD

**Issue by blumpy1** [reaper-oss/sws#1472] opened 2020-11-30 04:33 UTC
I frequently use Transpose selected midi items - down semitone, up semitone, down octave, and up octave.

Upon the latest version of SWS these Actions only work on the first selected item and not all of the selected midi items as it did it previous versions and as described.

Thank you!

**Comment by cfillion** [comment] 2020-11-30 06:16
Closing as duplicate of #1429.

**Closed by cfillion** 2020-11-30 06:16 UTC
