### ISSUE TITLE
SWS/BR: (Toggle) Preview media item under mouse at track fader volume(/through track) (/and pause during preview): unexpected outcomes on audio 

### ISSUE THREAD

**Issue by liperli** [reaper-oss/sws#1189] opened 2019-09-03 10:14 UTC
Hi, am working in Reaper 5.982 64 bit, Windows 10

When I run either 'preview-' or 'toggle preview media item under mouse through track and pause during playback' on Audio tracks/items, with either the whole media item 'or starting from mouse' variations, the cursor stops and playback pauses but there is no sound, no preview.

(...on Midi tracks/items, however, all seem to work as intended)

For Audio items/tracks, the same 'preview item' options, but without the 'pause during playback' element, work variably in terms of volume. The 'through track' option works as intended, but the 'at track fader volume' plays at significantly different (in this case, louder) level than the pre-fx level as set and heard during straightforward reaper transport playback (the simpler action/s '(/toggle) preview media item under mouse' play back louder still, although here I would have expected an increase in volume).

Any indicators gratefully received

**Comment by cfillion** [comment] 2019-09-17 03:54
Thanks! The preview bug when paused should be fixed in this build: [sws-2.10.0.1-Windows-x64-f27f7fa3.exe](https://ci.appveyor.com/api/buildjobs/gmr7c8i4xxafpai0/artifacts/build%2Fsws-2.10.0.1-Windows-x64-f27f7fa3.exe).

I'm unable to reproduce the volume issue in a fresh project. Audio items seems to obey the track volume as expected here. Is there any specific steps I need to do to make it fail?

**Comment by liperli** [comment] 2019-09-23 09:59
Thanks for your attention, will try that out and maybe a closer look at the volume issue when I can

**Closed** 2019-10-14 18:32 UTC
Labels: bug
