### ISSUE TITLE
Raspberry pi version / download please

### ISSUE THREAD

**Issue by swschilke** [reaper-oss/sws#1468] opened 2020-11-24 22:05 UTC
It would be nice if this could be downloaded from the end user site.

Thanks

**Comment by cfillion** [comment] 2020-11-24 22:09
Closing as duplicate of #1340.

**Closed by cfillion** 2020-11-24 22:09 UTC

**Comment by swschilke** [comment] 2020-11-25 06:39
> 
> 
> Closing as duplicate of #1340.

Well, I'm after Raspberry Pi OS, it's a Linux flavour but different architecture then Intel Linux. So is that covered with the bleeding edge sws-2.12.1.0-Linux-armv7l-4ae1b75b.tar.xz ? Or is that "only" for Unbuntu (on ARM)?

Kind regards and keep up the good work

.

**Comment by cfillion** [comment] 2020-11-25 07:19
`sws-2.12.1.0-Linux-armv7l-4ae1b75b.tar.xz` is the correct build for use on a Raspberry Pi running a 32-bit Linux OS. It has nothing Ubuntu-specific.

**Comment by swschilke** [comment] 2020-11-25 07:33
Thank you for your support!
