### ISSUE TITLE
After we use save snap shot, Reaper doesn't recall well the most recent render settings (bug)

### ISSUE THREAD

**Issue by ovnis82** [reaper-oss/sws#1595] opened 2021-12-31 00:30 UTC
After we use save snap shot, Reaper doesn't recall well the most recent render settings because it adds always second render *.wav even we have no secondary output export inside our recent render settings.
The bug happens when we save snap shot while the render window is closed.

**Comment by nofishonfriday** [comment] 2022-01-03 15:36
@ovnis82 
Hm...I can't reproduce so far.
What I did:
- Open Render to File dialog (to make sure there's no Seocondary output format set)
- Close Render to File dialog
- Save SWS snapshot
- Run action: File: Render project, using the most recent render settings

Result: Only Primary output format is rendered, also there is no Secondary output format set

Could you give steps to reproduce in case I missed something, or a screencapture?
Also, which Operating system/Reaper/SWS version?

**Comment by ovnis82** [comment] 2022-01-05 17:09
Instead of "Render project, using the most recent render settings", you have to use "Render project to disk..." action.

**Comment by nofishonfriday** [comment] 2022-01-05 22:40
Still can't reproduce.
Can you post a screencapture?
Here's what I've tried:
![secondary output](https://user-images.githubusercontent.com/7658194/148299784-7c4d7dcc-f10f-4882-9b3e-bb2f9baa9e0d.gif)

**Comment by ovnis82** [comment] 2022-01-12 22:16
Do you know where I can find files or folder about sws data save, please?

**Comment by ovnis82** [comment] 2022-01-12 22:40
I have made a Reaper regular installation and it seems solved.  Previously I used only Reaper Update Utiliy for the Reaper installation.

**Comment by nofishonfriday** [comment] 2022-01-12 23:35
Thanks for the feedback.
So closing this issue now (if still not solved, post again and we can reopen).

**Closed by nofishonfriday** 2022-01-12 23:35 UTC
