### ISSUE TITLE
Playlist management: errors in cropping, appending or pasting

### ISSUE THREAD

**Issue by tormyvancool** [reaper-oss/sws#1204] opened 2019-10-10 14:30 UTC
I have issues with the playlist manager
Once a playlist is made, it execute it finely

But once I chose for Crop or Append or Paste, the final result is totally incorrect.
Items are missing,  or partially copied and pasted.

I attached a .zip file containing a video that shows you the details.

I would like to know if this is an issue or it's me badly operating, and what do you suggest for the best.

[Reaper-Playlist-Issue.zip](https://github.com/reaper-oss/sws/files/3713085/Reaper-Playlist-Issue.zip)

**Comment by cfillion** [comment] 2019-10-11 00:21
Interesting, can you share the project RPP? Are any media items grouped?

**Comment by tormyvancool** [comment] 2019-10-21 14:18
> Interesting, can you share that TEST.RPP project? Are any media items grouped?


Sorry for the late reply
About the media items: not any group
Yes sure, the TEST.RPP is here in attachment in the ZIP file
[TEST.zip](https://github.com/reaper-oss/sws/files/3751273/TEST.zip)

**Comment by cfillion** [comment] 2019-10-23 00:39
I cannot reproduce the bug with SWS v2.10.0. "Paste playlist at edit cursor" behaves as expected here with that project.

There is a possibility some REAPER setting is interfering. Can you share your reaper.ini as well?

**Comment by nofishonfriday** [comment] 2019-10-24 16:19
I can reproduce if I have Preferences (-> Project) -> Media Items Defaults: Overlap and crossfade items when splitting (length is set to 0:00.010 here). enabled when pasting here.
I have that pref assigned to the toolbar button shown in the gif.

https://i.imgur.com/PeL633Z.gif

**Comment by cfillion** [comment] 2019-10-25 01:22
Fixed in this build: [sws-2.11.0.0-Windows-x64-e12769f5.exe](https://ci.appveyor.com/api/buildjobs/cguxsl5xw1yjjo7s/artifacts/build%2Fsws-2.11.0.0-Windows-x64-e12769f5.exe).

**Closed** 2019-10-28 05:14 UTC
Labels: bug

**Comment by tormyvancool** [comment] 2019-10-29 11:41
Yep it works perfectly. Thanks a million!

**Comment by tormyvancool** [comment] 2019-10-29 12:07
P.S. testing it closely I did notice that when you Crop project on new tab, the zones are replicated but not into the new position but they are referred to the original project.
Thus it will be necessary to manually move or recreate the zones.

Did you get the same result?

**Comment by cfillion** [comment] 2019-11-17 09:59
"Crop project to playlist" and "Crop project to playlist (new project tab)" should produce the same output.
