### ISSUE TITLE
Empty S&M_Cyclactions.ini and cycle action editor after "Apply change" function

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1451] opened 2020-11-08 09:23 UTC
It happened once in the past, and it happened again. Just after "apply change" in the cycle action editor, all cycle actions disappear from the cycle action editor (instantaneous disapearance), and S&M_Cyclactions.ini is mostly empty : there still is one or two actions, but all the rest has vanished. Quite a horror story scenario if you don't have backups (hopefully I have one) ^^.

Thank you

**Comment by lowlou** [comment] 2020-11-08 13:14
Here is the Cyclaction.ini. If you try to apply change to this file, all cycle action are deleted.

https://gofile.io/d/8suAjC

**Comment by lowlou** [comment] 2020-11-08 17:22
So I went thru the the txt file, trying to see if I have an action that goes beyond 8192 characters, but no, max is around 7500 characters.

**Comment by cfillion** [comment] 2020-11-09 02:30
Which action are you changing and what is the change? Given the symptoms it's probably a duplicate of #1439 (I don't have a fix for that ready yet).

**Comment by cfillion** [comment] 2020-11-09 05:56
Never mind, I found the issue. There is an additional limit on Windows: an entire section cannot reliably contain more than 65,535 bytes in the .ini. This second ceiling doesn't apply on macOS and Linux.

( The `Main_Cyclactions` section in the .ini above has 1,053,598 bytes.)

**Comment by lowlou** [comment] 2020-11-09 06:24
Argh... So what can be done at the user level ? Transform some actions in script with the template you posted earlier ? Is there any chance that this problem could have a solution ?

**Comment by cfillion** [comment] 2020-11-09 06:36
> Is there any chance that this problem could have a solution?

I'm fixing the data loss issue. I'll also explore a few possible ways to avoid being hit by the limit, but I can't give a guarantee on that right now.

**Comment by lowlou** [comment] 2020-11-09 06:47
Thanks :) !!! I'll have to adapt for the time being.

**Comment by lowlou** [comment] 2020-11-09 14:56
I've seen your edit : Ok so if the limit is one million that would explain why the bug appears just now, not long before. This limit explains (I think) most of the issues I've been reporting here lately. I might have to rely on scripts more for now on, and try to reduce the cycle action count. 

Thanks for your help, have a nice day ! :)

**Comment by lowlou** [comment] 2020-12-06 07:48
Any update on a possible lift of the 1 million bytes ceiling for the .ini file ? I regularly hit the limit, it has become very difficult to get anyhting done in a quick & safe way. I have to convert cycle actions into scripts, making them hard to tweak in the future, in order to implement anything. It's a really difficult situation in Reaper now. If there is any way to lift the ceiling I'd be very glad !

**Comment by cfillion** [comment] 2020-12-06 07:55
I removed the limit in the PR linked above. It won't be included in the next release (2.12.1.1) though, but the one after (probably 2.13).

**Comment by lowlou** [comment] 2020-12-06 07:58
Oh wow that's an amazing news :) ! Thanks Cfillion for this, big time !

**Comment by lowlou** [comment] 2020-12-06 11:50
Downloaded, and now problem totally solved :). I will avoid any SWS update until it's officially implemented then. thank you very very much Cfillion. I'll give a bit of money at the end of the month !
xxxxxxxx

**Comment by lowlou** [comment] 2020-12-08 01:30
Well... Actually I still end up with some Cycle action into parenthesis, actions that are fine otherwise, again it's the latest ID in the list (around 850). I have weird behaviors where, script or custom actions are not registered completely (ID = 0, or script not found in the action list), then with a Close and reopen Reaper, the script/custom/cycle action appear. But then, other cycle actions are put into parenthesis. It seems that new scripts put older cycle actions into parenthesis ? There seems to be a threshold that I'm crossing there ?Could be also that I'm above the global number of action that Reaper can scan ? I can't really count the global number, so cannot tell.

**Comment by cfillion** [comment] 2020-12-08 01:37
That's #1436, a separate issue where you're reaching REAPER's maximum action limit. Next update (not 2.12.1.1) will show a warning message when cycle actions fails to be added when clicking on Apply. The limit itself is not on SWS side so I can't remove that one.

https://forum.cockos.com/showthread.php?t=243459

**Comment by lowlou** [comment] 2020-12-08 01:45
^^ Yes I got the two topics mixed up, sorry. Clear explanation, I'll have to clean the action list then !

**Comment by lowlou** [comment] 2020-12-08 02:03
& I'm so fucked, Reapack was installing everything, always, and I was not paying attention. facepalm

**Comment by cfillion** [comment] 2020-12-08 02:11
Disable "Install new packages when synchronizing" in *Extensions > ReaPack > Manage repositories > Options*. Then uninstall anything packages you're not using in *Browse packages*. That should free up a few hundred slots...

**Comment by lowlou** [comment] 2020-12-20 20:27
I'd just like to mention, after using this special version for a few weeks, that it works, but I get random crash when registering new actions. I'm above the 1 million w10 limit. and sometimes "apply change" in the cycle action editor bugs, resulting in a total reaper crash. It disapears, poof ^^. When I open a new session, all datas are fine, even the new one I was trying to save (the crash seems to wait until the very end of the "apply change" calculation). I think you could reproduce the crash by simply trying several "apply change" in a row with a very big Cycle (for one Cyclaction.ini  that goes above the 1 mo limit) action list (I'm at ID 880 and some cycle actions are super big).

**Comment by cfillion** [comment] 2020-12-20 22:09
Please send a "Dump file" of reaper.exe taken using the Windows task manager when it crashes.

**Comment by lowlou** [comment] 2020-12-21 21:37
will do

**Comment by lowlou** [comment] 2021-01-23 06:17
Sorry but I don't know how to do that : Reaper is not in the processes when it crashes.

**Comment by cfillion** [comment] 2021-01-23 12:20
Does it show the "REAPER has stopped working" dialog? reaper.exe should still be in the process list while that dialog is still open.

Sometimes the crash dialogs may are disabled in Windows 10. Here's how to enable them: https://superuser.com/a/1349113.

**Comment by lowlou** [comment] 2021-01-23 12:34
No Reaper disapears. Pouf. No dialog. Ok I'll follow the instructions on this page, and next time the Reaper bug happens & it crashes, I'll be READY :p. 
xxxxxxxxxxx

**Closed** 2021-12-20 21:40 UTC
Labels: bug
