### ISSUE TITLE
Error in Lua-docs for SNM_GetSetSourceState

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1497] opened 2021-01-19 15:16 UTC
There is a , missing in the Lua-docs of SNM_GetSetSourceState and SNM_GetSetSourceState2:

boolean reaper.SNM_GetSetSourceState(MediaItem item, **integer takeidxWDL_FastString state**, boolean setnewvalue)

boolean reaper.SNM_GetSetSourceState2(**MediaItem_Take takeWDL_FastString state**, boolean setnewvalue)

The other entries are fully intact.

**Comment by cfillion** [comment] 2021-01-19 15:35
Confirmed. The separator is omitted before custom types in the Lua function signatures. These SWS functions are affected:

- SNM_GetProjectMarkerName
- SNM_GetSetSourceState
- SNM_GetSetObjectState
- SNM_GetSourceType

Closing this because it's a bug in REAPER.

**Closed by cfillion** 2021-01-19 15:35 UTC
