### ISSUE TITLE
Feature request for Loudness analyzer - analyze time selection for master output

### ISSUE THREAD

**Issue by dali-dbr** [reaper-oss/sws#977] opened 2018-04-29 11:27 UTC
Hi.

Could it be done the loudness analyzer would analyze the time selection of the master output. 

It would basically just create a temporary master export file any analyze it.  That would save a lot of time when mastering for broadcast.

If I chose Analyze selected track and select Master track it will not work.

Thank you

![bbb](https://user-images.githubusercontent.com/6317229/39406093-56e260e8-4bb1-11e8-987d-db24fdcb087c.jpg)

Br,
Dali

**Comment by nofishonfriday** [comment] 2018-04-30 15:11
Hi,

as you noticed, loudness analyzes as implemented in SWS currently only works on files not, realtime output.
So doing it via a temporary render as you suggested would be the way to go indeed.
However, afaik we don't have currently full access to render / render settings so it can't be _completely_ automated.

I've just uploaded a script to ReaPack which maybe comes close enough though. ('Analyze loudness of master output in time selection (via temp render).lua')

![an loud temp](https://user-images.githubusercontent.com/7658194/39434314-89a61c4e-4c98-11e8-89e0-b304c3473373.gif)

(It automatically deletes the rendered temp file after analyzing also on HD to avoid file clutter.)

Note that to properly work you must make the following settings in the Render dialog before:
![Render settings](https://i.imgur.com/g04Mlgd.jpg)

If you give it a try, let me know how it works for you.

**Comment by dali-dbr** [comment] 2018-05-01 08:31
Hi.

Thank you.

I have just installed Reapack and I don't see this script among 1013 packages included.

What am I missing?

Thank you
Br,
Dali

**Comment by dali-dbr** [comment] 2018-05-01 08:57
I have imported a repository using this link.

Use this link for importing:
https://raw.githubusercontent.com/nofishonfriday/ReaScripts/master/index.xml

27 packages will install OK, but not this one :(

https://github.com/nofishonfriday/ReaScripts/raw/c5481914f055cb01f61c30bbd55333bbac4c59a3/Loudness/Analyze%20loudness%20of%20master%20output%20in%20time%20selection%20(via%20temp%20render).lua:
  HTTP response code said error (22): The requested URL returned error: 404 Not Found

Thank you

Br,
Dali

**Comment by nofishonfriday** [comment] 2018-05-01 11:00
Sorry for the trouble.
I tend to forget mentioning that my ReaPack repo must be imported manually into ReaPack.
But you figured that out meanwhile. :)

I also could reproduce the HTTP response code error, not sure what went wrong there, but please do a 'Synchronize packages' in ReaPack and then try installing again, should be fixed now (it's here at least).

Let me know...

**Comment by dali-dbr** [comment] 2018-05-01 11:57
It works great , thank you.

I don't like that I need to change project render dialog back and forth as those paths and settings are project specific, but I am aware of limitation though.

Thank you!

Br,
Dali

**Comment by nofishonfriday** [comment] 2019-02-06 16:00
Needs REAPER API addition.

**Closed by nofishonfriday** 2019-02-06 16:00 UTC

**Comment by nofishonfriday** [comment] 2019-04-07 23:07
Since necessary API was added in REAPER 5.974, a script doing this is now available in [ReaPack](https://reapack.com/): 'Analyze loudness of master output in time selection (via temp render)'.
(via [nofish ReaScript repository](https://github.com/nofishonfriday/ReaScripts))
