### ISSUE TITLE
bug with action "switch item source file to next in folder"

### ISSUE THREAD

**Issue by x-tropic** [reaper-oss/sws#1353] opened 2020-05-18 20:54 UTC
OS Mojave 10.14.6
Reaper 6.10
SWS 2.10.0

I have a problem with sorting files in the action "switch item source file to next in folder." Files always change in the random list. If you switch back and forth, you will notice that the sequence is saved.
I tried running Reaper with the default configuration. I tried different folders with sample libraries on different disks of the system SSD. I tried to create a new user account, and I also installed Reaper and SWS on another laptop! I can’t believe my eyes, how can such a bug happen on two different computers?
If, for example, i use the TAL-Sampler, then in it the sorting of files during switching occurs normally. I have not experienced such problems in other DAWs. Helps please.

**Comment by cfillion** [comment] 2020-05-18 22:34
The order of the files is as given by the filesystem and is not guaranteed to be alphabetical, in fact they are likely not sorted in any particular order.

I agree it would make more sense to use alphabetical order. Can you try this build? https://cfillion.ca/files/sws/sws-2.12.0.0-Darwin-x86_64-sort-switch-source-file-in-folder-c31af5d6.dmg

**Comment by x-tropic** [comment] 2020-05-18 22:42
> The order of the files is as given by the filesystem and is not guaranteed to be alphabetical, in fact they are likely not sorted in any particular order.
> 
> I agree it would make more sense to switch the source files in their alphabetical order. Can you try this build? https://cfillion.ca/files/sws/sws-2.12.0.0-Darwin-x86_64-sort-switch-source-file-in-folder-c31af5d6.dmg

yes! it's work! Big thanks, i'm happy)))

**Comment by x-tropic** [comment] 2020-06-05 14:42
Hello! I noticed that after installing the recommended build, I started random crashes. They happen at any time, even when I can do nothing in Reaper, but just select an item for example.
Yesterday I tried to replace the SWS version with a stable one from the site and for the second day I have no problems. Most likely there is a memory leak somewhere. Could you check? I already laid out the logs, but then I did not know what was the matter. You can see system logs here:  https://forum.cockos.com/showthread.php?p=2298349#post2298349

**Comment by cfillion** [comment] 2020-06-05 21:15
Those files are CPU usage analysis taken during runtime, not crash reports. Are you getting freezes? (If so, SWS doesn't appear to be responsible according to those logs.)

If you are instead getting crashes, please post the crash reports.

**Comment by x-tropic** [comment] 2020-06-05 22:03
> Those files are runtime performance analysis reports, not crash reports. Are you getting freezes? (If so, SWS doesn't appear to be responsible according to those logs.)
> 
> If you are instead getting crashes, please post the crash reports.

I don’t know what reports to provide, because reaper can randomly complete work without any confirmation and I see only a system report about the crash. The second day I use the version of SWS from the official site (on which I have problems on apfs file system) and everything works very stably. Tell me, what other data can I provide to help localize the problem?

**Comment by cfillion** [comment] 2020-06-05 22:06
You can find past crash reports in Console.app under User Reports. Crash reports are the file with the ".crash" extension.

**Comment by x-tropic** [comment] 2020-06-05 22:08
> You can find past crash reports in Console.app under User Reports. Crash reports are the file with the ".crash" extension.

Last report.
[REAPER_2020-06-04-142049_iMac-X-Tropic.crash.zip](https://github.com/reaper-oss/sws/files/4738688/REAPER_2020-06-04-142049_iMac-X-Tropic.crash.zip)

**Comment by cfillion** [comment] 2020-06-05 22:17
Thanks! That bug (it's #1359) will be fixed in the next update. Did you save a screenset prior to that crash (could be minutes or even hours before it actually crashed)?

**Comment by x-tropic** [comment] 2020-06-05 22:23
> Thanks! That bug (it's #1359) will be fixed in the next update. Did you save a screenset prior to that crash (could be minutes or even hours before it actually crashed)?

Unfortunately no, every time this happened suddenly. I could just do audio or MIDI editing, twist plug-in options, and so on ...
I attach the rest of the logs from the same folder. Thanks a lot and have a nice day.
[crash logs.zip](https://github.com/reaper-oss/sws/files/4738727/crash.logs.zip)

**Comment by cfillion** [comment] 2020-06-05 22:33
Two of those crashes were caused by AU plugins: `audio.schulz.OszillosMegaScope` and `com.keilwerthAudio.VPS-Avenger`. The rest is that SWS bug above (which makes it randomly crash some time after saving a screenset, although there might be other unknown triggers).

**Comment by x-tropic** [comment] 2020-06-05 22:37
> Two of those crashes were caused by AU plugins: `audio.schulz.OszillosMegaScope` and `com.keilwerthAudio.VPS-Avenger`. One of them seems to come from REAPER itself, but is inconclusive. The rest is that SWS bug above (which makes it randomly crash some time after saving a screenset, although there might be other yet unknown ways to trigger it).

Ok, I will keep in mind, thanks.

**Closed** 2020-10-16 21:40 UTC
