### ISSUE TITLE
Really after update SWS 2.8.8.0 drug-zoom has a problem.Image freezes and cursor jumps.

### ISSUE THREAD

**Issue by Frankie177** [reaper-oss/sws#859] opened 2017-04-03 08:16 UTC
![bug zoom](https://cloud.githubusercontent.com/assets/26865153/24600783/d991108e-185e-11e7-887c-03b0b37aa1c8.gif)

**Comment by swstim** [comment] 2017-04-06 03:22
Duplicate of #842.

**Closed by swstim** 2017-04-06 03:22 UTC
