### ISSUE TITLE
BUG: CF_GetClipboard has a limit on the length of the clipboard contents

### ISSUE THREAD

**Issue by dsyrock** [reaper-oss/sws#1391] opened 2020-07-04 04:39 UTC
When I use CF_GetClipboard('') to fetch content that is too long, I get incomplete results. And version 2.11 totally normal.

**Comment by cfillion** [comment] 2020-07-04 15:09
Yeah, 2.12 accidentally broke the dynamic buffer reallocation. It will be fixed in 2.12.1 (via #1367).

Closing as duplicate of #1365.

**Closed by cfillion** 2020-07-04 15:09 UTC
