### ISSUE TITLE
Not working: SWS/wol: Adjust envelope or track height under mouse cursor...

### ISSUE THREAD

**Issue by ericzang** [reaper-oss/sws#1287] opened 2020-01-14 09:14 UTC
v6.03
Hi cfillion, you may know already (I see some other height related posts), but this command no longer is working. And I think the other associated commands. Thanks! (work around is to use native Inc/Dec selected track heights. Though is less flexible/ergonomic).

SWS/wol: Adjust envelope or track height under mouse cursor, zoom center to mouse cursor (MIDI CC relative/mousewheel)

**Comment by cfillion** [comment] 2020-01-14 19:28
The next SWS pre-release will contain the fix for this and all related actions.

Closing as duplicate of #1240.

**Closed by cfillion** 2020-01-14 19:28 UTC
