### ISSUE TITLE
Snapshots: automation on Send Volume not restored

### ISSUE THREAD

**Issue by hgs42** [reaper-oss/sws#833] opened 2017-02-08 22:45 UTC
An automation on the volume of a send will be not restored.

It' easy to reproduce: Create an automation track on a send volume, make a snapshot, restore the snapshot and the automation track disapears.

regards
Herbert

**Comment by nofishonfriday** [comment] 2017-03-15 13:21
duplicate of   #537

**Closed** 2017-03-15 14:17 UTC
