### ISSUE TITLE
Region Playlist broken with Undo 

### ISSUE THREAD

**Issue by bewareofthemonkey** [reaper-oss/sws#1747] opened 2023-04-01 14:31 UTC
Working on a project with SWS v2.12.1 #3 . 
Performing an Undo will delete all the existing SWS playlist !

**Comment by nofishonfriday** [comment] 2023-04-01 20:39
Closing as duplicate of #1743.
Please see [here](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1492561166) for a possible (admittedly not nice) workaround for now.
As it stands currently, this needs to be addressed/fixed from Reaper side (report in Reaper forum is [already posted](https://forum.cockos.com/showthread.php?t=277781)).

**Closed by nofishonfriday** 2023-04-01 20:39 UTC
