### ISSUE TITLE
Project state data loss via undo (track notes, region playlists...)

### ISSUE THREAD

**Issue by gaetanonicolosi** [reaper-oss/sws#1743] opened 2023-03-17 14:54 UTC
Hello,

I already posted this issue on Reaper forum, and someone (nofish) suggested to post the issue also here!
I have been using the SWS Notes (Notepad) to write notes on each track, and all of sudden they disappear? I had Reaper v6.77 when that happen, and I updated to v6.78 but it didn't fix the problem. The SWS extension is v2.12.1.3. I did a search, and I couldn't find a solution. Can anyone help please? This has happened a few times also in the past, but I can't remember what action caused it. 

I updated the SWS extension to the latest beta v2.13.2.0 built Jan 16th 2023, but the track notes didn't appeared, I believe they are gone for good.
Very disappointed, but I knew that the track notes wouldn't magically appear again. I hope this update will prevent that this issue continue. But, I just found out that the SWS beta update didn't fix the issue, the track notes disappear after I duplicate a midi track. And the track notes will disappear on all the tracks, I tried to Undo, but all the track notes are gone for good.

I only had one project open when that happened, and I couldn't reproduce the issue by start a new project and duplicate the midi track with items either.
But I know that is what happened! On the project that I was working on, I wrote some notes on new tracks and as soon as I duplicated a midi track all the notes were gone. It Happened two times. That's the most relevant info I can give, but I don't know 100% if that's what caused it. Please, I hope this issue can be fixed soon, the track notes for me it's a valuable feature to organize the entire project.
Any advise?

Thanks for your attention!
Gaetano

**Comment by cfillion** [comment] 2023-03-18 02:09
No luck duplicating so far. Tried in a blank project:

1. Create 5 tracks with MIDI items inside
2. Wrote some track notes on each
3. Selected all and ran the action "Track: Duplicate tracks"

Result: The original 5 tracks kept their notes and the new duplicates had blank notes.

I did find that it is possible to lose some notes when undoing but I doubt that is the bug you got since it only deletes notes since the last undo point (not all notes in the whole project unless they were all written in one go).

1. Create two tracks
2. Write some track notes for each
5. Create a third track
6. Undo

Result: The first two tracks lose their notes because the notes are part of the third track insertion's undo point.

**Comment by gaetanonicolosi** [comment] 2023-03-18 19:39
I can't duplicate the issue either, but like you mentioned, It did happened also after an undo action  that deleted a track note that added later after.

P.S. I want to mentioned that there weren't track notes on the midi tracks that I duplicated. The track notes were on all the drum tracks, and Keys tracks containing wav items. I am not sure if that can help, but I will try to give as much as info I can.

**Comment by gaetanonicolosi** [comment] 2023-03-24 17:55
Here is an update!

I am sure 100% now that it's the undo action causing the the disappearance of the track notes, because I saw it happened.

- I was recording and when I stopped the recording, I did the undo with ctrl+z. So I checked the track notes by opening the track note window, and they were deleted (all of them). So, I left the track window opened and then I click on re-do Icon and the track notes appeared again.

-I saved the project (so I would not loose the track notes).

- While the track note window was still opened I clicked to record for a few seconds, I stopped, I did again ctrl+z once and the track note were still there, but I did a second time ctrl+z and the track notes were gone for good. Clicking the icon re-do did not make the track notes appeared again.

-I opened a new project with a template that has track notes. And I was able to reproduce the same issue by doing the following:
Record a few seconds, stop recording, and click the undo icon 3 times.

I hope this info will lead to a fix.

**Comment by nofishonfriday** [comment] 2023-03-25 01:14
Since this comes up repeatedly recently, maybe related to this?
> v6.76 - February 28 2023
>  + Undo: exclude registered project extension state from undo [p=2514972]

**Comment by gaetanonicolosi** [comment] 2023-03-25 01:27
I have no idea, but here is a video that show the issue:

[https://drive.google.com/file/d/1bOH...ew?usp=sharing](https://drive.google.com/file/d/1bOHn3Hr6axhEmRIcNnWkUi2oXDIPLhMW/view?usp=sharing)

**Comment by Sonorityscape** [comment] 2023-03-25 02:09
Hey! So I have been seeing this as well. I think there are different ways to trigger it but here is one way that I can repro 100% of the time (and is simple).

- Create a track or tracks and add some SWS notes to them
- Create a time selection ('Time Selection Change' in the Undo History)
- Undo that change and the SWS notes get deleted.

**Comment by Sonorityscape** [comment] 2023-03-25 02:16
Follow up...

Also using the action 'Time selection: Remove (unselect) time selection and loop points' and then hitting undo also deletes the notes.

**Comment by gaetanonicolosi** [comment] 2023-03-25 02:17
> Hey! So I have been seeing this as well. I think there are different ways to trigger it but here is one way that I can repro 100% of the time (and is simple).
> 
>     * Create a track or tracks and add some SWS notes to them
> 
>     * Create a time selection ('Time Selection Change' in the Undo History)
> 
>     * Undo that change and the SWS notes get deleted.

I just did the same think as you did, and sure enough the track note were gone.

**Comment by Sonorityscape** [comment] 2023-03-25 02:17
Looks like any time selection related action is doing it.

**Comment by nofishonfriday** [comment] 2023-03-25 14:39
> Hey! So I have been seeing this as well. I think there are different ways to trigger it but here is one way that I can repro 100% of the time (and is simple).
> 
>     * Create a track or tracks and add some SWS notes to them
> 
>     * Create a time selection ('Time Selection Change' in the Undo History)
> 
>     * Undo that change and the SWS notes get deleted.

This goes back to at least Reaper 6.0/SWS v2.12.1 #3 (just tested), so probably not related to the change I mentioned above.

**Comment by gaetanonicolosi** [comment] 2023-03-25 19:58
Here is some update!

Thanks to xpander for this suggestion posted on the Reaper forum, it's good to uncheck the time selection in undo history (Preferences/General, Undo settings), at least until there is a fix for it.

Like xpander mentioned on the previous post, it's not just the time selection and undo cause the issue.

I opened a project
I set the cursor to a different position
undo

and the track notes were deleted.
I guess we may need to uncheck the cursor position in undo history (Preferences/General, Undo settings). Or maybe DO NOT UNDO at all.

Here is a video that shows what happened
https://drive.google.com/file/d/1bDlyb7eBFEhiN615y--6vKODpMQD_Cbo/view?usp=share_link

**Comment by zappazapper** [comment] 2023-03-30 15:48
I'd just like to contribute my own experience with this issue, if it helps. If any additional information is required, don't hesitate to ask.

I'm using the Region Playlist to audition drum takes. Whenever I hit CTRL-Z, all my playlists disappear. I read on the Reaper forum and in this thread to try disabling Time Selection in the Undo settings in Preferences > General, but it doesn't seem to have any effect on the issue.

Thank you for any advice on a possible solution, and a big thanks to those of you who develop these tools and try to fix them when there's an issue. Even though I have to rebuild my playlists every time I hit CTRL-Z out of habit, this tool is still saving me tons of time.

**Comment by gaetanonicolosi** [comment] 2023-03-30 16:00
> I'd just like to contribute my own experience with this issue, if it helps. If any additional information is required, don't hesitate to ask.
> 
> I'm using the Region Playlist to audition drum takes. Whenever I hit CTRL-Z, all my playlists disappear. I read on the Reaper forum and in this thread to try disabling Time Selection in the Undo settings in Preferences > General, but it doesn't seem to have any effect on the issue.
> 
> Thank you for any advice on a possible solution, and a big thanks to those of you who develop these tools and try to fix them when there's an issue. Even though I have to rebuild my playlists every time I hit CTRL-Z out of habit, this tool is still saving me tons of time.

You may want to disable cursor position in Undo Settings in preference - General, because it will cause the same issue.
here is a link of a video I made to show it.
https://drive.google.com/file/d/1bDlyb7eBFEhiN615y--6vKODpMQD_Cbo/view?usp=share_link

I currently disabled both time selection and cursor position from Undo settings to all my projects to avoid to delete all my track notes. It's a feature we can't use until it's fixed or we'll lose data.
I hope that helps.

**Comment by zappazapper** [comment] 2023-03-30 16:19
> You may want to disable cursor position in Undo Settings in preference - General, because it will cause the same issue. 

Thanks, I'll try that and report if the issue persists.

**Comment by gaetanonicolosi** [comment] 2023-03-30 18:55
> EDIT: I just checked my settings and cursor position is not checked and I believe it was never checked. The only thing that is checked is "item". Thank you.

Good think to know! Like I said in my previous post, I am afraid of using the undo action, because I don't know if I am going to lose any data. I try to undo only when it's really a must, but that is a big handicap on my workflow. I hope this is going to be fixed really soon.

**Comment by zappazapper** [comment] 2023-03-30 21:10
> Good think to know! Like I said in my previous post, I am afraid of using the undo action, because I don't know if I am going to lose any data. I try to undo only when it's really a must, but that is a big handicap on my workflow. I hope this is going to be fixed really soon.

Yes, it certainly was a challenge not to succumb to the desire to just hit CTRL-Z whenever I did something wrong, but I managed to get through it and finish my edit. Fortunately the way I'm using the Region Playlist feature doesn't require me to remember anything to rebuild my playlists. Track notes aren't something I've needed so far, but ya, it would be devastating to lose those. The main reason I use Reaper over other DAWs is the community involvement in developing it and fixing things when they don't work as intended, so I have some amount of faith that the issue will be addressed at some point, because the people who's job it is to do that actually care.
 
> Feel free to share also your experience here https://forum.cockos.com/showthread.php?t=277263 so other Reaper users can see and we can share info as much as we can

XD I initially posted my issue on the Reaper forum and they said this was the right place for it. It seems to be getting more attention here anyway...

**Comment by nofishonfriday** [comment] 2023-03-31 16:00
@all
For region playlist at least I could now pin it down to the Reaper change I [mentioned above](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1483655281).
Maybe I haven't tested properly [here](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1483840744) but I suspect that's the cause for the other data losses we're seeing recently too (otherwise it would be quite a coincidence).
Will create a a report on the Reaper forum.

R6.75
![6 75](https://user-images.githubusercontent.com/7658194/229171214-7949d951-9a77-4ff3-97ee-9656c3f3ad77.gif)

R6.76
![6 76](https://user-images.githubusercontent.com/7658194/229171269-7bd9d9a0-da73-497d-b000-941284604523.gif)

**Comment by gaetanonicolosi** [comment] 2023-03-31 16:15
Thank you so much for the info. I appreciate all the work and the effort to resolve the issue!

**Comment by zappazapper** [comment] 2023-03-31 19:40
> @ALL For region playlist at least I could now pin it down to the Reaper change I [mentioned above](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1483655281). Maybe I haven't tested properly [here](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1483840744) but I suspect that's the cause for the other data losses we're seeing recently too (otherwise it would be quite a coincidence). Will create a a report on the Reaper forum. edit: Report: https://forum.cockos.com/showthread.php?t=277781

So is there anything that I can do to fix the problem on my end? Or is it something that has to be fixed in code?

**Comment by nofishonfriday** [comment] 2023-03-31 20:15
> So is there anything that I can do to fix the problem on my end? Or is it something that has to be fixed in code?

The hint [given above](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1490552237) to exclude cursor position/time selection from undo didn't prevent data loss for me with the Playlist test above.
So other than that (and avoiding doing undo in the first place, which is of course not really an option), we'll have to wait what Justin/schwa reply to the report, I'm afraid.

Another option would be to temporarily revert to [Reaper v6.75](https://www.reaper.fm/download-old.php) until then.
There the problem shouldn't happen (according to my tests above at least. Please report back if it does...)

**Comment by nofishonfriday** [comment] 2023-03-31 21:36
> Where's the appropriate place for SWS feature requests? Here or on the Reaper forum?

Also here on the issue tracker.

**Comment by gaetanonicolosi** [comment] 2023-04-01 01:39
> Another option would be to temporarily revert to [Reaper v6.75](https://www.reaper.fm/download-old.php) until then.
> There the problem shouldn't happen (according to my tests above at least. Please report back if it does...)

Thanks for the suggestion I reverted Reaper to v6.75 and It looks like it's working without losing any data. I will report if something comes up.

P.S. it's better  downgrading to v.6.75 VS not be able to use the undo action. Hopefully soon things will be fixed!

Thanks Again

**Comment by nofishonfriday** [comment] 2023-04-06 20:03
Issue should be fixed in just released REAPER v6.78+dev0406 (for pre-release versions, if anyone wants to test, see [here](https://forum.cockos.com/showthread.php?t=22836)).

**Comment by gaetanonicolosi** [comment] 2023-04-07 13:45
> Issue should be fixed in just released REAPER v6.78+dev0406 (for pre-release versions, if anyone wants to test, see [here](https://forum.cockos.com/showthread.php?t=22836)).

I just installed REAPER v6.78+dev0406 and did a quick test, and it looks like it's fixed! THANK YOU!
Now I can undo with no loos of data.

P.S. is it safe to use the pre-release verision to finish my project, or it's better waiting for the official release?

**Comment by nofishonfriday** [comment] 2023-04-23 21:12
REAPER 6.79 which contains this fix was just released, so closing this issue.
If it should still persist after updating, please open a new issue.

**Closed by nofishonfriday** 2023-04-23 21:12 UTC
