### ISSUE TITLE
BR_GetMouseCursorContext_Track() bug: can be off by a few tracks

### ISSUE THREAD

**Issue by n0ner** [reaper-oss/sws#1308] opened 2020-02-14 07:20 UTC
Hi!

Not really sure how to reproduce this as it just happens sometimes. BR_GetMouseCursorContext_Track() can be off by a few tracks (usually it thinks the mouse is over a few tracks higher). Scrolling doesn't always solve it right away, resizing track heights seems to fix it.

**Comment by nofishonfriday** [comment] 2020-02-14 15:59
Hi,

which SWS version are you using?
If the current official version (v2.10.0 #1) please try with the current [beta version](https://www.sws-extension.org/download/pre-release/).
There are fixes in the current beta for `BR_GetMouseCursorContext` in Reaper v6, so I'd assume (hope) it should be fixed there.

**Comment by n0ner** [comment] 2020-02-14 16:54
Thanks for the quick response!

Using Reaper 6 and the beta, but pretty sure I had it on the official too.

**Comment by nofishonfriday** [comment] 2020-02-14 18:16
I think @cfillion did some additional tweaks/fixes for this for the next (not yet officially released) beta, he may comment further on it.

**Comment by cfillion** [comment] 2020-03-08 02:31
I can reproduce this issue by moving REAPER 6's main window from to a display with a different DPI scaling settings. BR_GetMouseCursorContext_Track gets an offset over the arrange view but gives the correct track over the TCP. I'll look into it later.

**Comment by cfillion** [comment] 2020-03-09 12:47
It's not related to DPI after all (altough DPI switching does trigger it due to the window resize). I can reliably duplicate with these steps:

1. Create enough tracks fill more than one screen
2. Resize down REAPER's window
3. Scroll to the bottom of the arrange view
4. Maximize the window

However resizing tracks has no effect for me.

**Closed** 2022-05-07 14:29 UTC
Labels: bug
