### ISSUE TITLE
"SWS: Open Projects From List" broken in v2.11.0.0 08d3c6fc

### ISSUE THREAD

**Issue by Hambone68** [reaper-oss/sws#1329] opened 2020-04-06 16:04 UTC
In the latest pre-release build (v2.11.0.0 08d3c6fc), when using the "SWS: Open Projects From List" action, if you answer YES to the "Close Active Tabs First" prompt, all projects get closed as expected. However, each new project gets opened and then immediately closed, resulting in only one open project (the last in the list) when the action completes.
This works properly in the 2.10 stable release, not sure about pre-releases prior to the one listed.

**Comment by cfillion** [comment] 2020-04-06 17:18
This will be addressed in the next pre-release. Closing as duplicate of #1293.

**Closed by cfillion** 2020-04-06 17:18 UTC
