### ISSUE TITLE
SWS Notes disappear after Undo

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1880] opened 2024-07-24 20:08 UTC
**I guess duplicate of https://github.com/reaper-oss/sws/issues/1812**

I've noticed that changes in the Notes do make the project dirty but no undo point is created in the Undo history. Maybe this is the reason why when the last action which immediately followed or preceded Notes editing is undone the Notes changes are undone as well.

Re-doing restores both the change in REAPER and in the Notes.

Alongside my own GIF i'm uploading another user's demo of the issue from the thread [[t=277263]](https://forum.cockos.com/showthread.php?t=277263#40) 
(also linked here https://github.com/reaper-oss/sws/issues/1743#issuecomment-1483661629)

![NOTES](https://github.com/user-attachments/assets/c4621f26-f74f-4906-8a29-5f53b9c3a499)

https://github.com/user-attachments/assets/8953d493-5399-46f9-abb9-eeb46504c1c8

**Comment by cfillion** [comment] 2024-07-27 02:08
Closing as duplicate of the mentioned other issue.

**Closed by cfillion** 2024-07-27 02:08 UTC
