### ISSUE TITLE
request : Options to trigger actions in the Cycle action window

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1408] opened 2020-09-04 19:05 UTC
Hello

I'm doing long cycle action, and sometimes (often) they don't work as expected. To find where the error is, I like to execute all action manually to find where it's not working. Right now, I have to - type each actions in the action list - find the action - clic "run". It's ok with 10 actions. With 200 actions, it's super super slow. 

Could it be possible to trigger each steps of cycle actions from the Cycle action window instead ? A right clic, or a button at the top or bottom of the cycle action window ? 

That would be super welcome :) 
Thanks !
Louis

**Comment by cfillion** [comment] 2021-02-06 00:08
Closing as duplicate of #825.

**Closed by cfillion** 2021-02-06 00:08 UTC
