### ISSUE TITLE
SWS: Quantize item's start to grid (keep length) not working for Automation Items.

### ISSUE THREAD

**Issue by vanhaze2000** [reaper-oss/sws#1039] opened 2018-08-14 18:06 UTC
Situation:
An Item with underneath it an Automation Item.
When i execute the Action: "SWS: Quantize item's start to grid (keep length)" the Item will be snapped to Grid
but the Automation Item is not, it's start position is not changed, also not when i have enabled "envelope points move with media items"

I make much use of this great SWS action and i am really hoping it will work eventually for Automation Items also.

Warm Regards and thanks for the great SWS !

**Comment by cfillion** [comment] 2018-09-11 19:01
It's not a bug, this action only moves items without affecting automation envelopes. "Quantize selected automation items to grid" could be done as a separate action though (script).

**Comment by vanhaze2000** [comment] 2018-09-11 20:04
Hi Christian !

Thank you for your support !
I am aware it is not a bug :0)

My only wish would be that media items, together with underlying automation item(s), that have the very same startpoint as media item,
could be quantized to grid in 1 go.

I assume a script "Quantize selected automation items to grid” would be welcome for starters.
Is it it much work to make that Script ?

I am willing to donate for it.

Warm Regards,
Rob.

**Comment by cfillion** [comment] 2018-09-11 20:56
Here's a quick test prototype: https://gist.github.com/cfillion/abc2128e7b00bfa2e4121684a7706c15.

**Comment by vanhaze2000** [comment] 2018-09-12 09:51
This is so awesome, thank you really much Christian, i am really happy with this !

Warm Regards,
Rob.



On Sep 11, 2018, at 10:56 PM, Christian Fillion <notifications@github.com> wrote:

Here's a quick test prototype: https://gist.github.com/cfillion/abc2128e7b00bfa2e4121684a7706c15.

**Comment by nofishonfriday** [comment] 2018-09-17 15:20
Sounds like we can close this?

@vanhaze2000
If you think otherwise just say so and we can always reopen. :)

**Closed** 2018-09-17 15:20 UTC
