### ISSUE TITLE
Sws extension take Fx big

### ISSUE THREAD

**Issue by svijayrathinam** [reaper-oss/sws#938] opened 2017-12-18 17:24 UTC
Hi,

I found an issue with the copy pasting of take fx with SWS extension. 

Scenario : I have an "X" media item where I have a 6 in 6 out plugin as take fx. I have a "y" media item with no plugins. Now I want to copy the plugins from the "X" item to "Y" clip item.

For this I use these shortcuts.

SWS/S&M: Copy FX Chain (Depending on Focus)

and then

SWS/S&M: Paste FX Chain (Depending on Focus)

When I do this the "Y" media item only has 2in6 out in the plugin pin configuration. Then I have to manually open the plugin and then modify the plugin I/O config to 6 in 6 out.

But if I just cmd drag and drop the take fx from "X" item to "Y" item then I dont have this problem. This is why I am sure that this is a SWS extension bug.

Can you pls fix this ?
svijayrathinam is online now  Report Post

**Comment by nofishonfriday** [comment] 2017-12-19 16:54
Confirmed.

Reason (@devs):
The Copy action copies the TAKEFX chunk but misses the TAKEFX_NCH line becuase it's outside of the chunk.

(https://i.imgur.com/us4z1Kh.jpg)

I've been looking into it but don't know how to fix currently as it's (again) dealing with the ChunkParserPatcher which I don't fully understand. I'll continue trying but if anyone else wants to tackle this, it's also welcome of course.

**Comment by nofishonfriday** [comment] 2017-12-20 16:18
Hi,

asking just in case, have you tried pressing Play after you've pasted the FX chain ?
Here at least when I do the above steps it also pastes with 2in/6out as you say, but it updates the In configuartion to 6 automatically when I press Play.

!(https://i.imgur.com/IA20wnd.gif)

**Comment by svijayrathinam** [comment] 2017-12-21 10:39
Yes.. I have tried that..This doesn't happen to me...Check the below Link

https://drive.google.com/file/d/11pG2HUftlQsHeVnH1T7HdtEzJ9E3Oa2b/view?usp=sharing

**Comment by svijayrathinam** [comment] 2017-12-21 11:18
![gif_fast](https://user-images.githubusercontent.com/34658126/34253709-c1558962-e66e-11e7-8c26-9461e4202c24.gif)

**Comment by nofishonfriday** [comment] 2017-12-24 00:18
Thanks for the screencapture.
Could you please test with the version linked below and let us know if it works for you ?
(I don't have the plugin you're using, so I can't test with it here.)

https://www.dropbox.com/s/r9y1xobok16mw9u/sws_osx.dmg?dl=1

Note:
It's a version only meant for testing, so don't forget to reinstall the current official SWS version afterwards.

Thanks.

**Comment by svijayrathinam** [comment] 2017-12-24 07:48
Hi Thank you very much for your work. I tried this. But the problem is still there. If you want the plugin you can download the trial here

http://www.iosono-sound.com/vstaax-plug-ins/

Its not just with this plugin but with every plugin.

**Comment by nofishonfriday** [comment] 2017-12-24 20:20
Ah, I almost missed it in the screencapture, you have a default preset set for the plugin, this means the correct channel assigment is done automatically when inserting the plugin, right ?

Not sure yet, but seems to me what's happening is that the the default preset (and thus the channel assignment) is not propagated when copy / pasting via the SWS action. I'll try to investigate further.

(As always, help from other SWS collaborators appreciated).

**Comment by svijayrathinam** [comment] 2018-01-08 18:43
Yes. It works with the test version now..Sorry I didn't install the test version in the right folder. When will this be released officially Pls ?

**Comment by nofishonfriday** [comment] 2018-01-10 18:55
Thanks for testing and reporting back, good to know it also works for you.
I'm hoping a fix will be in the next official SWS version but I don't know currently when this will be.

**Comment by svijayrathinam** [comment] 2018-01-19 06:02
Hello, Problem again..But now in a different form...The same bug is back on version 5.71 Pre13icc version. Here is the link. Pls help

https://www.dropbox.com/s/3zayw4x1yfurncv/Take%20FX%20Copy%20and%20Paste%20bug%20on%20multichannel%20Plugins.mov?dl=0

**Comment by svijayrathinam** [comment] 2018-01-26 15:36
Any Update on this pls ?

**Comment by nofishonfriday** [comment] 2018-01-29 01:08
Can you confirm it worked correctly in 5.70 but broke in 5.71pre ?
If yes, there have been changes to VST handling in 5.71pre which may affect this issue.
Please wait until 5.71pre16 is out (should be in the next days) where the changes will be reverted..
Then please try with 5.71pre16 (with the SWS test version I posted above) and report back if the bug is still present. Thanks.

**Comment by nofishonfriday** [comment] 2018-02-04 19:14
@devs

The original issue (as I understand) is that  the TAKEFX_NCH line is not part of the TAKEFX chunk and so doesn't get copied via SWS/S&M: Copy FX Chain (Depending on Focus) resulting in setting the pasted item FX chain back to 2 channels.

![takefx_nch](https://user-images.githubusercontent.com/7658194/35781162-9b53d05c-09e6-11e8-879a-9181c0d215ad.jpg)

My [patch](https://github.com/nofishonfriday/sws/commit/4becb1fbb514afcf1753c80529a5ef05b7ed1d64) seems to fix (also confirmed by OP above) but I'm hesitant submitting as PR because of risk of corrupting projects (when modifying chunk) so I'd appreciate review / help.

Would probably better to fix directly in [SNM_FXChainTakePatcher](https://github.com/reaper-oss/sws/blob/400c3c13949805afc37b87627a0c8664f436508f/SnM/SnM_Chunk.cpp#L177) but I don't good enough to do that.

**Comment by nofishonfriday** [comment] 2018-03-12 16:04
Justin says it's ok..
https://askjf.com/index.php?q=4041s

**Comment by svijayrathinam** [comment] 2018-06-08 14:41
Hi This take fx channel bug is still not fixed in ver 2.9.8. 

Can you pls fix this ?

I reported this long time ago and nofish made a temporary fix. But Now I find new feautures in SWS extension ver 2.9.8 that I want to use. But the old bug still remains..Can you pls fix this ? if not..@nofish could you pls make another temporary fix with the new version ?

**Closed** 2019-02-06 06:59 UTC
