### ISSUE TITLE
region playlist does not retain playlists bug

### ISSUE THREAD

**Issue by jnlundberg** [reaper-oss/sws#1744] opened 2023-03-20 08:47 UTC
After a few minutes all playlists are gone from the Region Playlist. I love the region playlist, I hope there is a fix. Should I try out the beta?

Reaper v6.78 - March 14 2023
SWS v2.12.1.3 featured build (February 6, 2021)
Mac OSX Monterery 12.6.3
MacBookPro 2015 15"

**Comment by cfillion** [comment] 2023-03-20 18:54
Could be related to #1743 (region playlist and track notes use a similar storage mechanism), first seen at the beginning of the month. There's also been a very suspicious [crash report](https://forum.cockos.com/showthread.php?p=2659581) (SWS auto-color, same data storage method) pointing to that.

Need to find a reliable way to trigger the data loss to investigate. Playlist didn't disappear when I created 2 region playlists in a blank project with 2 regions, closed the playlist window, waited 15 minutes, re-opened the playlist window.

> Should I try out the beta?

Generally yes: we've made a lot of fixes since 2.12. And if the bug ever causes a crash it would be easier to look into reports made with the latest version rather than a 2 years old version.

**Comment by jnlundberg** [comment] 2023-03-24 13:45
As a temporary fix I went back to Reaper v6.71 - November 28 2022 and so far has the problem not occurred again.

**Comment by cfillion** [comment] 2023-03-25 00:46
Closing as duplicate of #1743. I've observed both notes and region playlist getting lost at the same time via undo so now I'm convinced it's the same problem. Further findings should be posted there.

**Closed by cfillion** 2023-03-25 00:46 UTC
