### ISSUE TITLE
regions & notes

### ISSUE THREAD

**Issue by LarsOde** [reaper-oss/sws#1389] opened 2020-06-24 18:22 UTC
Hi, Im using a large song for our live set, each song has it's own region. I use hotkeys to jump to the next region (reaper builtin) via a footswitch. I also have attached the SWS note window to show the region name. With some songs, when I jump to the region, the region name is not shown in the notes window, only shortly after I press play. A lot of songs it's ok, but some not... I can't see a difference in the regions why that would happen...

**Comment by nofishonfriday** [comment] 2020-06-24 20:05
Could you perhaps upload a stripped down example project which shows the issue (containing just a few regions where it happens)?

**Comment by LarsOde** [comment] 2020-06-24 21:11
This is the actual file, without any media, I hope this works. You can jump between songs with number keys too (our old way of navigating). In the  future I want to jump to regions using a USB footcontroller, that's why I need to show the region number in the notes windows for everyone to see whats next ;)

[raa_live_reaper2.zip](https://github.com/reaper-oss/sws/files/4827919/raa_live_reaper2.zip)

**Comment by nofishonfriday** [comment] 2020-06-25 23:47
Thanks for the project.
I'm not sure though what I should be looking for. In the screencapture below I first go to regions 1 to 10 via shortcuts and the rest of the containing regions via action list (as I don't have shortcuts mapped for them) and all region names show up in the SWS notes window as far as I can tell.
What am I missing? :)

![regions](https://user-images.githubusercontent.com/7658194/85806151-867ea400-b74e-11ea-9cfe-d6c4e5a3d31a.gif)

**Comment by LarsOde** [comment] 2020-06-26 13:38
hm, strange... what screening tool did you use there? Then I can show you ;)

**Comment by nofishonfriday** [comment] 2020-06-26 22:29
https://www.cockos.com/licecap/

**Comment by LarsOde** [comment] 2020-06-26 22:43
ok, it's strange ;) when I jump with my configured region jumpers (I only use forward/backward), it seems ok. When I use my markers with hotkeys (in that file 1-2-3-and so on) for some songs it doesn't show the region name, even if the marker is in the same spot as the region start ;)
![reaper](https://user-images.githubusercontent.com/34895186/85906643-34518780-b80f-11ea-86bb-50f57821a9d4.gif)

**Comment by nofishonfriday** [comment] 2020-06-27 18:15
Ok, reproduced, if there's a marker at the exact same place where a region starts, it sometimes blocks the region name display, but not always.
Hm..trying to figure out why..

**Comment by nofishonfriday** [comment] 2020-06-27 21:55
update:
On further investigation I don't think this is a SWS bug because when double-clicking a region where this happens (e.g. Region 1) to set time selection to it, then do a 'Crop project to selection' the marker at region start (marker 1 in this case) is gone, meaning Reaper also 'thinks' the marker is outside the region.

I don't know how/why that happened but you can fix it relatively easy by moving the marker forth and back.

![region-fix](https://user-images.githubusercontent.com/7658194/85932956-abe7eb00-b8d1-11ea-93be-481ade2eb5f1.gif)

**Comment by nofishonfriday** [comment] 2020-10-24 21:38
closing as 'likely not a SWS bug'.

**Closed by nofishonfriday** 2020-10-24 21:38 UTC
