### ISSUE TITLE
"SWS/BR actions that play from mouse cursor position and solo track under mouse for the duration" is broken

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1180] opened 2019-08-17 15:38 UTC
I'm using Justins SWS build on Windows 10 with Reaper 5.981 dev0814 and there's a problem with the action. Executing it once will work flawlessly, but having done that, the GUI goes nuts (artefacts and Reaper becomes unusable).
Also, executing it a second time creates a time selection.
Have a look at the GIF:

https://nextcloud.stephanroemer.net/index.php/s/c2AqSDQcYgwT4Yo

**Comment by justinfrankel** [comment] 2019-08-17 19:24
This is also the same on 5.981+release SWS. The issue is that the BR mouse playback actions will call PreventUIRefresh(1), set a timer, then call PreventUIRefresh(-1) later to restore it. This is not safe to do (triggering the stop via ReaScript causes the state to get corrupted)... I've pushed a commit on next to fix this.

**Comment by nofishonfriday** [comment] 2019-10-16 15:44
Justin's fix was merged into `master` in https://github.com/reaper-oss/sws/commit/2fc46c3e603ffe581a5bf8903d26f61843473650.

**Closed by nofishonfriday** 2019-10-16 15:44 UTC
